<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>driving-telemetry</artifactId>
    <version>1.0.0</version>
    <modules>
        <module>telemetry</module>
        <module>telemetry/producer-app</module>
        <module>telemetry/consumer-app</module>
        <module>analytics</module>
        <module>analytics/algorithms</module>
        <module>analytics/algorithms/algorithm-base</module>
        <module>analytics/algorithms/algorithm-speed</module>
        <module>analytics/algorithms/algorithm-dummy</module>
        <module>analytics/analyze-app</module>
    </modules>
    <packaging>pom</packaging>
</project>
